# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.ImageField(upload_to='images/', verbose_name='ファイル'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='img',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
