# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_uploader', '0002_auto_20160921_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('file', models.FileField(upload_to=easy_uploader.models.get_upload_to, verbose_name='ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_uploader.Category')),
            ],
        ),
    ]
