# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easy_uploader', '0004_auto_20161030_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easy_uploader.Category', verbose_name='カテゴリ'),
        ),
    ]
